version: '3.5'
services:
  database:
    network_mode: host
    image: mongo:3.4-jessie
    volumes:
      - db_data:/data/db
    restart: unless-stopped
  defichain:
    network_mode: host
    image: defi/defichain:1.3.0
    environment:
      - NETWORK=${NETWORK:?NETWORK env required}
    volumes:
      - node_data:/data
      - ./defi.${NETWORK}.conf:/data/defi.conf
    restart: unless-stopped
  bitcore-node:
    network_mode: host
    build: .
    image: bitcore-node
    command: "bash -c 'cd ./packages/bitcore-node/; npm run tsc; node build/src/server.js'"
    environment:
      - NETWORK=${NETWORK:?NETWORK env required}
      - API_PORT=${API_PORT:-3000}
      - DB_HOST=localhost
      - CHAIN=DFI
      - BITCORE_CONFIG_PATH=bitcore.config.json
      - BITCORE_NODE_FILE_LOG=${BITCORE_NODE_FILE_LOG:-false}
      - BITCORE_NODE_SENTRY_DNS=${BITCORE_NODE_SENTRY_DNS:-false}
      - DISABLE_HEALTH_CRON=${DISABLE_HEALTH_CRON:-false}
    volumes:
      - ./bitcore.testnet_local.config.json:/usr/src/app/bitcore.config.json
    depends_on:
      - database
      - defichain
    restart: unless-stopped
  insight:
    network_mode: host
    build: .
    image: insight
    command: ["npm", "run", "insight-previous:prod"]
    environment:
      - NETWORK=${NETWORK:?NETWORK env required}
      - API_PREFIX=${API_PREFIX:?API_PREFIX env required}
      - HTTP_PORT=${HTTP_PORT:-5000}
      - ENV=prod
      - CHAIN=DFI
      - BITCORE_CONFIG_PATH=bitcore.config.json
    volumes:
      - ./bitcore.${NETWORK}.config.json:/usr/src/app/bitcore.config.json
    depends_on:
      - bitcore-node
    restart: unless-stopped
volumes:
  db_data:
  node_data:
